### ISSUE TITLE
No border should appear after change in focus

### ISSUE THREAD

**Issue by Gourav2609** [Gourav2609/TO_DO_LIST#1]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Gourav2609/TO_DO_LIST/assets/115522947/252e7f65-51c3-4895-863e-17c446059609)
the dotted border should not  appear

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kshitij-0711** [comment]
Hi @Gourav2609 . I have quite a knowledge of MERN stack, would you mind assigning this issue to me?

**Comment by Gourav2609** [comment]
@kshitij-0711 sure , here you go

**Comment by kshitij-0711** [comment]
is there a contribute.md file might help me set this project up locally

**Comment by Gourav2609** [comment]
go the root the file and run
`npm install`

then after then run
`npm start`

you will be directed to a local host on your local machine

**Comment by kshitij-0711** [comment]
Just made a PR please check it out , do let me know if there's any problem
