### ISSUE TITLE
About adding interactive animation while tick mark the task for completion

### ISSUE THREAD

**Issue by Hemant-Lohar** [Gourav2609/TO_DO_LIST#3]
We can add animation while marking out tasks like line over text.

**Comment by Hemant-Lohar** [comment]
Could you assign me so I can add this? I want to contribute.

**Comment by Gourav2609** [comment]
hello @Hemant-Lohar 
in which part/section are u talking about like the task will appear striked in the ALL section
you can do it like in the ALL section ...the task appears stricked but in the completion section it should appear normal

**Comment by Hemant-Lohar** [comment]
Yes we need to do it only for all section

**Comment by Gourav2609** [comment]
@Hemant-Lohar here u go

**Comment by Hemant-Lohar** [comment]
Done with it You can check the pull request.

**Comment by Hemant-Lohar** [comment]
@Gourav2609 change Repository topic to hacktoberfest and label as hacktoberfest-accepted. Its not Hactoberfext there is "K" missing. its guideline by hacktoberfest 23.
